In [1]:
import torch
import torchvision
import numpy as np
# Check for CUDA capabilities
print(torch.cuda.is_available())
# Check what is the default type
print(torch.get_default_dtype())

False
torch.float32


In [2]:
# Create a tensor
t = torch.Tensor([1,2,3])
if torch.cuda.is_available():
    t = t.cuda()

In [3]:
dd = [
[1,2,3],
[4,5,6],
[7,8,9]
]
# Create a tensor from a default Python object e.g.: list
d = torch.Tensor(dd)
print(d)
# Access the shape
print(d.shape, d.size())

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
torch.Size([3, 3]) torch.Size([3, 3])


In [4]:
# Access data type, device and layout
print(d.dtype)
print(d.device)
print(d.layout)

torch.float32
cpu
torch.strided


In [5]:
# Convert the data originally stored in numpy arrays
data = np.array([1,2,3])
data = torch.tensor(data)
print(data)

tensor([1, 2, 3])


In [6]:
# Get identity matrix, zero matrix and matrix of ones
print(torch.eye(2))
print(torch.zeros([2,2]))
print(torch.ones([2,2]))

tensor([[1., 0.],
        [0., 1.]])
tensor([[0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.]])


In [7]:
# Get a tensor of random values uniformly distributed
print(torch.rand([1,3,2,2]))

tensor([[[[0.7824, 0.0762],
          [0.6166, 0.5723]],

         [[0.0119, 0.2432],
          [0.5954, 0.5478]],

         [[0.8505, 0.1895],
          [0.3347, 0.8283]]]])


In [8]:
data = np.array([1,2,3])
type(data)

o1 = torch.Tensor(data)      # Cannot specify dtype
o2 = torch.tensor(data)
o3 = torch.as_tensor(data)   # Do not copy, but use the same memory reference <- The best option
o4 = torch.from_numpy(data)  # Do not copy, but use the same memory reference

# Use
# torch.tensor()
# torch.as_tensor()

print(o1)
print(o2)
print(o3)
print(o4)
# Convert a tensor to numpy array
print(o4.numpy())

tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([1, 2, 3])
tensor([1, 2, 3])
[1 2 3]


In [9]:
t = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
], dtype=torch.float32)
print(t.size(),t.shape)
# Conpute the rank of the tensor
print("Rank {}".format(len(t.size())))
# Compute the number of elements or access it from a default function
print("Number of elements {}".format(torch.tensor(t.size()).prod()))
print("Number of elements {}".format(t.numel()))

# Perform reshape on a tensor
print(t.reshape([1,12]))
print(t.reshape([1,12]).shape)

# Squeeze out a 1 dimension
print(t.reshape([1,12]).squeeze())
print(t.reshape([1,12]).squeeze().shape)

# Unsqueeze a 1 dimension 
print(t.reshape([1,12]).squeeze().unsqueeze(dim=0))
print(t.reshape([1,12]).squeeze().unsqueeze(dim=0).shape)

# Flatten a tensor and specify from where to start
print(t.flatten(start_dim = 0))

torch.Size([3, 4]) torch.Size([3, 4])
Rank 2
Number of elements 12
Number of elements 12
tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
torch.Size([1, 12])
tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])
torch.Size([12])
tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
torch.Size([1, 12])
tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])


In [10]:
# Concatenate two or multiple tensors with respect to a dimension 
t1 = torch.tensor([
    [1,2],
    [3,4]
])
t2 = torch.tensor([
    [5,6],
    [7,8]
])
print(torch.cat((t1,t2),dim=0))
print(torch.cat((t1,t2),dim=1))

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])


In [11]:
# Create three different matrices corresponding to three different inputs in a batch and stack them
t1 = torch.tensor([
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1]
])

t2 = torch.tensor([
    [2,2,2,2],
    [2,2,2,2],
    [2,2,2,2],
    [2,2,2,2]
])

t3 = torch.tensor([
    [3,3,3,3],
    [3,3,3,3],
    [3,3,3,3],
    [3,3,3,3]
])
t= torch.stack([t1,t2,t3])

In [12]:
# Add channel dimensions
t = t.reshape([3,1,4,4])

In [13]:
# Flatten inputs in a batch
t= t.flatten(start_dim = 1)

In [14]:
# concatenate multiple channels
r = torch.ones([1,2,2])
g = torch.ones([1,2,2]) + 1
b = torch.ones([1,2,2]) + 2
t = torch.cat([r,g,b], dim=0)
print(t,t.shape)

tensor([[[1., 1.],
         [1., 1.]],

        [[2., 2.],
         [2., 2.]],

        [[3., 3.],
         [3., 3.]]]) torch.Size([3, 2, 2])


In [15]:
# Completely flatten them
print(t.flatten())

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])


In [16]:
# Elementwise operations
t1 = torch.tensor([
    [1,2],
    [3,4]
], dtype=torch.float32)
t2 = torch.tensor([
    [9,8],
    [7,6]
], dtype=torch.float32)
print(t1+t2, t1<t2)

tensor([[10., 10.],
        [10., 10.]]) tensor([[True, True],
        [True, True]])


In [20]:
# Reduction operations
t = torch.tensor([
    [0,1,0],
    [2,0,2],
    [0,3,0]
], dtype=torch.float32)
# Dim = 1 along a row, dim = 0 along a column
print(t.sum(), t.mean(), t.std(), t.prod(), t.mean(dim=1),t.mean(dim=0), t.argmax(dim=1))
print(t.mean(dim=1).tolist())
print(t.mean().item())
print(t.mean(dim=1).numpy())

tensor(8.) tensor(0.8889) tensor(1.1667) tensor(0.) tensor([0.3333, 1.3333, 1.0000]) tensor([0.6667, 1.3333, 0.6667]) tensor([1, 2, 1])
[0.3333333432674408, 1.3333333730697632, 1.0]
0.8888888955116272
[0.33333334 1.3333334  1.        ]
